/*
 * Byron Picado Obando
 * I Proyecto Programado Programación III
 * Universidad Nacional de Costa Rica
 * Escuela de Informática
 */
package tienda.presentation.view;

import java.util.List;
import tienda.entities.Abono;
import tienda.entities.Apartado;
import tienda.presentation.controller.AbonosController;
import tienda.presentation.model.AbonoModel;

/**
 *
 * @author Byron
 */
public class AbonosView extends javax.swing.JDialog implements java.util.Observer{

    AbonoModel model;
    AbonosController controller;
    String id;
    String saldo;
    List<Abono> abonos;
    Apartado apartado;
    
    public AbonosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setController(AbonosController controller){
        this.controller = controller;
    }
    
    public void setModel(AbonoModel model){
        this.model = model;
        model.addObserver(this);
    }
    
     public void update(java.util.Observable updatedModel,Object parametros){
       this.pendienteLbl.setText(saldo);
       abonosTable.setModel(model.getPersonasModel());
       this.revalidate();
    }
     
     public void setIdApartado(String id){
         this.id = id;
     }
     
     public String getIdApartado(){
         return this.id;
     }
     
     public void buscar(){
         controller.buscar();
     }
     
     public void setSaldoPendiente(String saldo){
         this.saldo = saldo;
         model.addObserver(this);
     }

    public List<Abono> getAbonos() {
        return abonos;
    }

    public void setAbonos(List<Abono> abonos) {
        this.abonos = abonos;
    }

    public Apartado getApartado() {
        return apartado;
    }

    public void setApartado(Apartado apartado) {
        this.apartado = apartado;
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saldoLbl = new javax.swing.JLabel();
        pendienteLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        abonosTable = new javax.swing.JTable();

        saldoLbl.setText("Saldo pendiente: ");

        abonosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(abonosTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saldoLbl)
                        .addGap(34, 34, 34)
                        .addComponent(pendienteLbl)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoLbl)
                    .addComponent(pendienteLbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AbonosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable abonosTable;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel pendienteLbl;
    private javax.swing.JLabel saldoLbl;
    // End of variables declaration//GEN-END:variables
}
