/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda.presentation.view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import tienda.Application;
import tienda.presentation.controller.ApartadosController;
import tienda.presentation.controller.ClientesController;
import tienda.presentation.model.TiendaModel;

/**
 *
 * @author Marco
 */
public class ClientesView extends javax.swing.JDialog implements java.util.Observer{
    ClientesController controller;
    TiendaModel model;

    public ClientesController getController() {
        return controller;
    }

    public void setController(ClientesController controller) {
        this.controller = controller;
    }

    public TiendaModel getModel() {
        return model;
    }

    public void setModel(TiendaModel model) {
        this.model = model;
        model.addObserver(this);
    }

    
    /**
     * Creates new form ClienteView
     */
     public ClientesView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      this.setLocationRelativeTo(null);
      
    }
    public void update(java.util.Observable updatedModel,Object parametros){
       if (parametros != TiendaModel.CLIENTES_MODEL) return;
       nombreFld.setText(model.getFiltro().getNombre());
       clientesFld.setModel(model.getClientesModel());
       this.revalidate();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarBG = new javax.swing.ButtonGroup();
        buscarBtn = new javax.swing.JButton();
        nombreFld = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientesFld = new javax.swing.JTable();
        agregarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreRB = new javax.swing.JRadioButton();
        cedulaRB = new javax.swing.JRadioButton();
        apartadosBtn = new javax.swing.JButton();

        setTitle("Clientes");

        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        nombreFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFldActionPerformed(evt);
            }
        });

        clientesFld.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        clientesFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesFldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientesFld);

        agregarBtn.setText("Agregar Cliente");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por:");

        buscarBG.add(nombreRB);
        nombreRB.setSelected(true);
        nombreRB.setText("Nombre");

        buscarBG.add(cedulaRB);
        cedulaRB.setText("Identificación");

        apartadosBtn.setText("Ver Apartados");
        apartadosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartadosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apartadosBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addComponent(nombreRB)
                                .addGap(34, 34, 34)
                                .addComponent(cedulaRB))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreFld, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreRB)
                    .addComponent(cedulaRB)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBtn))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(agregarBtn)
                        .addGap(155, 155, 155)
                        .addComponent(apartadosBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // TODO add your handling code here:
    private void nombreFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFldActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
         controller.buscar();
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
         Application.CLIENTE_VIEW.setLocation(this.agregarBtn.getLocationOnScreen());
 //controller.preAgregar();
         Application.CLIENTE_VIEW.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void clientesFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesFldMouseClicked
         if (evt.getClickCount() == 2) {
         int row = this.clientesFld.getSelectedRow();
         Application.CLIENTE_VIEW.setLocation(evt.getLocationOnScreen());
         controller.editar(row);
      }        // TODO add your handling code here:
    }//GEN-LAST:event_clientesFldMouseClicked

    private void apartadosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartadosBtnActionPerformed
       
        int row = this.clientesFld.getSelectedRow();
        if (!this.clientesFld.isRowSelected(row)) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "ERROR AL MOSTRAR, DEBE HABER SELECCIONADO UN CLIENTE", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{
            controller.listarApartados(row);
        }
        
    }//GEN-LAST:event_apartadosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarBtn;
    public javax.swing.JButton apartadosBtn;
    public javax.swing.ButtonGroup buscarBG;
    public javax.swing.JButton buscarBtn;
    public javax.swing.JRadioButton cedulaRB;
    public javax.swing.JTable clientesFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombreFld;
    public javax.swing.JRadioButton nombreRB;
    // End of variables declaration//GEN-END:variables
}
