/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda.presentation.view;

import java.util.Observable;
import javax.swing.JOptionPane;
import tienda.Application;
import tienda.entities.Usuario;
import tienda.presentation.controller.UsuarioController;
import tienda.presentation.model.UserModel;

/**
 *
 * @author William
 */
public class FormularioUsuario extends javax.swing.JDialog implements java.util.Observer{

    UserModel model;
    UsuarioController controller;

    public UserModel getModel() {
        return model;
    }

    public void setModel(UserModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public UsuarioController getController() {
        return controller;
    }

    public void setController(UsuarioController controller) {
        this.controller = controller;
    }
    
    /**
     * Creates new form FormularioUsuario
     */
    public FormularioUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dependienteRB = new javax.swing.JRadioButton();
        administradorRB = new javax.swing.JRadioButton();
        nombreTex = new javax.swing.JTextField();
        contaseTex = new javax.swing.JTextField();
        nombrelbl = new javax.swing.JLabel();
        contraselbl = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        tipolbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(dependienteRB);
        dependienteRB.setText("Dependiente");

        buttonGroup1.add(administradorRB);
        administradorRB.setText("Administrador");

        nombrelbl.setText("Nombre");

        contraselbl.setText("Contraseña");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");

        tipolbl.setText("Tpo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrelbl)
                            .addComponent(contraselbl))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreTex, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(contaseTex)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Guardar)
                        .addGap(50, 50, 50)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(tipolbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(dependienteRB)
                        .addGap(51, 51, 51)
                        .addComponent(administradorRB)))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrelbl))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contaseTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contraselbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dependienteRB)
                    .addComponent(administradorRB)
                    .addComponent(tipolbl))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(cancelar))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        this.controller.guardar();
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioUsuario dialog = new FormularioUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Guardar;
    public javax.swing.JRadioButton administradorRB;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton cancelar;
    public javax.swing.JTextField contaseTex;
    public javax.swing.JLabel contraselbl;
    public javax.swing.JRadioButton dependienteRB;
    public javax.swing.JTextField nombreTex;
    public javax.swing.JLabel nombrelbl;
    public javax.swing.JLabel tipolbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(java.util.Observable updatedModel,Object parametros) {
        if (parametros != UserModel.USUARIO_CURRENT) return;
       
       Usuario clienteCurrent = model.getUsuarioCurrent();
        
       this.nombreTex.setEnabled(model.getModo()==Application.MODO_AGREGAR);
       
       nombreTex.setText(clienteCurrent.getNombre());
       if (model.getErrores().get("nombre")!=null){
            nombrelbl.setBorder(Application.BORDER_ERROR);
            nombrelbl.setToolTipText(model.getErrores().get("nombre"));
        }
        else{
            nombrelbl.setBorder(null);
            nombrelbl.setToolTipText("");
        }

        this.contaseTex.setText(clienteCurrent.getContraseña());
        if (model.getErrores().get("contraseña")!=null){
            this.contraselbl.setBorder(Application.BORDER_ERROR);
            contraselbl.setToolTipText(model.getErrores().get("contraseña"));
        }
        else{
           contraselbl.setBorder(null);
           contraselbl.setToolTipText("");
        }
        if(clienteCurrent.getTipo()=="super"){
            this.administradorRB.setSelected(true);
        }
        else
            this.dependienteRB.setSelected(true);
        
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
