/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda.presentation.view;

import javax.swing.JOptionPane;
import tienda.Application;
import tienda.entities.Cliente;
import tienda.presentation.controller.ClienteController;
import tienda.presentation.model.TiendaModel;


public class FormularioCliente extends javax.swing.JDialog implements java.util.Observer {
    TiendaModel model;
    ClienteController controller;

    public TiendaModel getModel() {
        return model;
    }

    public void setModel(TiendaModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public ClienteController getController() {
        return controller;
    }

    public void setController(ClienteController controller) {
        this.controller = controller;
    }
    
    public FormularioCliente(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoFld = new javax.swing.ButtonGroup();
        idLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        idFld = new javax.swing.JTextField();
        nombreFld = new javax.swing.JTextField();
        apellido1Lbl = new javax.swing.JLabel();
        apellido2Lbl = new javax.swing.JLabel();
        direccionLbl = new javax.swing.JLabel();
        telefonoLbl = new javax.swing.JLabel();
        apellido1Fld = new javax.swing.JTextField();
        apellido2Fld = new javax.swing.JTextField();
        direccionFld = new javax.swing.JTextField();
        telefonoFld = new javax.swing.JTextField();
        guardarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setTitle("Cliente");
        setResizable(false);

        idLbl.setText("Id");

        nombreLbl.setText("Nombre");

        apellido1Lbl.setText("Primer Apellido");

        apellido2Lbl.setText("Segundo Apellido");

        direccionLbl.setText("Dirección");

        telefonoLbl.setText("Teléfono");

        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(apellido2Lbl)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(direccionLbl)
                                            .addGap(57, 57, 57)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(telefonoLbl)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telefonoFld, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellido2Fld, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(direccionFld)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLbl)
                                    .addComponent(idLbl)
                                    .addComponent(apellido1Lbl))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idFld, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellido1Fld, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(nombreFld)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(guardarBtn)
                        .addGap(62, 62, 62)
                        .addComponent(cancelarBtn)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLbl)
                    .addComponent(idFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLbl)
                    .addComponent(nombreFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido1Lbl)
                    .addComponent(apellido1Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido2Lbl)
                    .addComponent(apellido2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(direccionLbl)
                    .addComponent(direccionFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoLbl)
                    .addComponent(telefonoFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
         controller.guardar(); 
          
    }//GEN-LAST:event_guardarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
         this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apellido1Fld;
    public javax.swing.JLabel apellido1Lbl;
    public javax.swing.JTextField apellido2Fld;
    public javax.swing.JLabel apellido2Lbl;
    public javax.swing.JButton cancelarBtn;
    public javax.swing.JTextField direccionFld;
    public javax.swing.JLabel direccionLbl;
    public javax.swing.JButton guardarBtn;
    public javax.swing.JTextField idFld;
    public javax.swing.JLabel idLbl;
    public javax.swing.JTextField nombreFld;
    public javax.swing.JLabel nombreLbl;
    private javax.swing.ButtonGroup sexoFld;
    public javax.swing.JTextField telefonoFld;
    public javax.swing.JLabel telefonoLbl;
    // End of variables declaration//GEN-END:variables
    
   public void update(java.util.Observable updatedModel,Object parametros){
       if (parametros != TiendaModel.CLIENTE_CURRENT) return;
       
       Cliente clienteCurrent = model.getClienteCurrent();
        
       this.idFld.setEnabled(model.getModo()==Application.MODO_AGREGAR);
       
       idFld.setText(clienteCurrent.getId());
       if (model.getErrores().get("id")!=null){
            idLbl.setBorder(Application.BORDER_ERROR);
            idLbl.setToolTipText(model.getErrores().get("id"));
        }
        else{
            idLbl.setBorder(null);
            idLbl.setToolTipText("");
        }

        nombreFld.setText(clienteCurrent.getNombre());
        if (model.getErrores().get("nombre")!=null){
            nombreLbl.setBorder(Application.BORDER_ERROR);
            nombreLbl.setToolTipText(model.getErrores().get("nombre"));
        }
        else{
           nombreLbl.setBorder(null);
           nombreLbl.setToolTipText("");
        }
        apellido1Fld.setText(clienteCurrent.getPrimerApellido());
        if (model.getErrores().get("primer apellido")!=null){
            this.apellido1Lbl.setBorder(Application.BORDER_ERROR);
            this.apellido1Lbl.setToolTipText(model.getErrores().get("primer apellido"));
        }
        else{
           this.apellido1Lbl.setBorder(null);
           this.apellido1Lbl.setToolTipText("");
        }
         apellido2Fld.setText(clienteCurrent.getSegundoApellido());
         if (model.getErrores().get("segundo apellido")!=null){
            this.apellido2Lbl.setBorder(Application.BORDER_ERROR);
            this.apellido2Lbl.setToolTipText(model.getErrores().get("segundo apellido"));
        }
        else{
           this.apellido2Lbl.setBorder(null);
           this.apellido2Lbl.setToolTipText("");
        }
          direccionFld.setText(clienteCurrent.getDireccion());
        if (model.getErrores().get("direccion")!=null){
            this.direccionLbl.setBorder(Application.BORDER_ERROR);
            this.direccionLbl.setToolTipText(model.getErrores().get("direccion"));
        }
        else{
           this.direccionLbl.setBorder(null);
           this.direccionLbl.setToolTipText("");
        }
         telefonoFld.setText(clienteCurrent.getTelefono());
        if (model.getErrores().get("telefono")!=null){
            this.telefonoLbl.setBorder(Application.BORDER_ERROR);
            this.telefonoLbl.setToolTipText(model.getErrores().get("telefono"));
        }
        else{
           this.telefonoLbl.setBorder(null);
           this.telefonoLbl.setToolTipText("");
        }
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
    } 
}
