/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda.presentation.view;

import javax.swing.JOptionPane;
import tienda.Application;
import tienda.entities.Producto;
import tienda.presentation.controller.ProductoController;
import tienda.presentation.model.ProductoModel;
import tienda.presentation.model.ProductoModel;

/**
 *
 * @author Marco
 */
public class FormularioProducto extends java.awt.Dialog implements java.util.Observer{

    /**
     * Creates new form FormularioProducto
     */
    public FormularioProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
     ProductoController controller;
    ProductoModel model;

    public ProductoController getController() {
        return controller;
    }

    public void setController(ProductoController controller) {
        this.controller = controller;
    }

    public ProductoModel getModel() {
        return model;
    }

    public void setModel(ProductoModel model) {
        this.model = model;
        this.model.addObserver(this);
    }
    
    public void update(java.util.Observable updatedModel, Object parametros) {
        if (parametros != ProductoModel.PRODUCTO_CURRENT) {
            return;
        }

        Producto prouctoCurrent = model.getProductoCurrent();

        //this.idFld.setEnabled(model.getModo()==Application.MODO_AGREGAR);
        //idFld.setText(clienteCurrent.getId());
        if (model.getErrores().get("id") != null) {
            this.idLbl.setBorder(Application.BORDER_ERROR);
            idLbl.setToolTipText(model.getErrores().get("id"));
        } else {
            idLbl.setBorder(null);
            idLbl.setToolTipText("");
        }

        //nombreFld.setText(clienteCurrent.getNombre());
        if (model.getErrores().get("color") != null) {
            this.Colorlbl.setBorder(Application.BORDER_ERROR);
            Colorlbl.setToolTipText(model.getErrores().get("color"));
        } else {
            Colorlbl.setBorder(null);
            Colorlbl.setToolTipText("");
        }
        //apellido1Fld.setText(clienteCurrent.getPrimerApellido());
        if (model.getErrores().get("talla") != null) {
            this.Tallalbl.setBorder(Application.BORDER_ERROR);
            this.Tallalbl.setToolTipText(model.getErrores().get("talla"));
        } else {
            this.Tallalbl.setBorder(null);
            this.Tallalbl.setToolTipText("");
        }
        //apellido2Fld.setText(clienteCurrent.getSegundoApellido());
        if (model.getErrores().get("valor") != null) {
            this.Valor.setBorder(Application.BORDER_ERROR);
            this.Valor.setToolTipText(model.getErrores().get("valor"));
        } else {
            this.Valor.setBorder(null);
            this.Valor.setToolTipText("");
        }
        //direccionFld.setText(clienteCurrent.getDireccion());
        if (model.getErrores().get("genero") != null) {
            this.Generolbl.setBorder(Application.BORDER_ERROR);
            this.Generolbl.setToolTipText(model.getErrores().get("genero"));
        } else {
            this.Generolbl.setBorder(null);
            this.Generolbl.setToolTipText("");
        }
        //telefonoFld.setText(clienteCurrent.getTelefono());
        if (model.getErrores().get("desc") != null) {
            this.descripcionLbl.setBorder(Application.BORDER_ERROR);
            this.descripcionLbl.setToolTipText(model.getErrores().get("desc"));
        } else {
            this.descripcionLbl.setBorder(null);
            this.descripcionLbl.setToolTipText("");
        }
        if (model.getErrores().get("cantidad") != null) {
            this.Cantidadlbl.setBorder(Application.BORDER_ERROR);
            this.Cantidadlbl.setToolTipText(model.getErrores().get("cantidad"));
        } else {
            this.Cantidadlbl.setBorder(null);
            this.Cantidadlbl.setToolTipText("");
        }
        this.validate();
        if (!model.getMensaje().equals("")) {
            JOptionPane.showMessageDialog(this, model.getMensaje(), "", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        FRb = new javax.swing.JRadioButton();
        Cantidadlbl = new javax.swing.JLabel();
        Generolbl = new javax.swing.JLabel();
        MRb = new javax.swing.JRadioButton();
        descripcionTex = new javax.swing.JTextField();
        AgregarBt = new javax.swing.JButton();
        CalcelarBt = new javax.swing.JButton();
        TipoTex = new javax.swing.JTextField();
        ValorTex = new javax.swing.JTextField();
        CantidadTex = new javax.swing.JTextField();
        idLbl = new javax.swing.JLabel();
        ColorTex = new javax.swing.JTextField();
        IdTex = new javax.swing.JTextField();
        Valor = new javax.swing.JLabel();
        Tallalbl = new javax.swing.JLabel();
        Colorlbl = new javax.swing.JLabel();
        descripcionLbl = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonGroup1.add(FRb);
        FRb.setText("F");

        Cantidadlbl.setText("Cantidad");

        Generolbl.setText("Genero");

        buttonGroup1.add(MRb);
        MRb.setText("M");

        AgregarBt.setLabel("Agregar");
        AgregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBtActionPerformed(evt);
            }
        });

        CalcelarBt.setText("Cancelar");
        CalcelarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcelarBtActionPerformed(evt);
            }
        });

        ValorTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTexActionPerformed(evt);
            }
        });
        ValorTex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorTexKeyTyped(evt);
            }
        });

        CantidadTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadTexActionPerformed(evt);
            }
        });
        CantidadTex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadTexKeyTyped(evt);
            }
        });

        idLbl.setText("IdProducto");

        ColorTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorTexActionPerformed(evt);
            }
        });

        Valor.setText("Valor");

        Tallalbl.setText("Talla");

        Colorlbl.setText("Color");

        descripcionLbl.setText("Descripción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Colorlbl)
                            .addComponent(Tallalbl)
                            .addComponent(Valor)
                            .addComponent(Generolbl)
                            .addComponent(idLbl))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ColorTex, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoTex, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValorTex, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdTex, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MRb)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AgregarBt)
                                            .addComponent(FRb))))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CalcelarBt)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Cantidadlbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(CantidadTex, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(descripcionLbl)
                        .addGap(18, 18, 18)
                        .addComponent(descripcionTex, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cantidadlbl)
                    .addComponent(CantidadTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLbl))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Colorlbl)
                    .addComponent(ColorTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tallalbl)
                    .addComponent(TipoTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valor)
                    .addComponent(ValorTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MRb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Generolbl)
                        .addComponent(FRb)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(descripcionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(descripcionTex, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBt)
                    .addComponent(CalcelarBt))
                .addGap(76, 76, 76))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void AgregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBtActionPerformed
        // TODO add your handling code here:

        this.controller.guardar();
    }//GEN-LAST:event_AgregarBtActionPerformed

    private void CalcelarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcelarBtActionPerformed
        this.setVisible(false);
        Application.HOME.setVisible(true);
    }//GEN-LAST:event_CalcelarBtActionPerformed

    private void ValorTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTexActionPerformed

    private void ValorTexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTexKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume(); // ignorar el evento de teclado
        }
    }//GEN-LAST:event_ValorTexKeyTyped

    private void CantidadTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadTexActionPerformed

    private void CantidadTexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadTexKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume(); // ignorar el evento de teclado
        }
    }//GEN-LAST:event_CantidadTexKeyTyped

    private void ColorTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorTexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioProducto dialog = new FormularioProducto(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AgregarBt;
    public javax.swing.JButton CalcelarBt;
    public javax.swing.JTextField CantidadTex;
    public javax.swing.JLabel Cantidadlbl;
    public javax.swing.JTextField ColorTex;
    public javax.swing.JLabel Colorlbl;
    public javax.swing.JRadioButton FRb;
    public javax.swing.JLabel Generolbl;
    public javax.swing.JTextField IdTex;
    public javax.swing.JRadioButton MRb;
    public javax.swing.JLabel Tallalbl;
    public javax.swing.JTextField TipoTex;
    public javax.swing.JLabel Valor;
    public javax.swing.JTextField ValorTex;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel descripcionLbl;
    public javax.swing.JTextField descripcionTex;
    public javax.swing.JLabel idLbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
