package tienda.presentation.view;

import tienda.Application;
import tienda.presentation.controller.HomeController;
import tienda.presentation.model.TiendaModel;

/**
 *
 * @author byron
 */
public class Home extends javax.swing.JFrame {
    HomeController controller;
    TiendaModel model;
    
    public void setController(HomeController controller){
        this.controller=controller;
    }
    public void setModel(TiendaModel model){
        this.model=model;
        
    }
    
   public void update(java.util.Observable updatedModel,Object parametros){
       
   }
    /**
     * Creates new form Cliente
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buscarClienteBoton = new javax.swing.JButton();
        agregarClienteBoton = new javax.swing.JButton();
        apartadoBuscarBoton = new javax.swing.JButton();
        ingresarApartadoBoton = new javax.swing.JButton();
        abonoBoton = new javax.swing.JButton();
        bienvenidaLabel = new javax.swing.JLabel();
        usuarioBt = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda");
        setResizable(false);

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda/presentation/view/resources/Log.png"))); // NOI18N
        logoLbl.setToolTipText("Bienvenido (a)");

        buscarClienteBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda/presentation/view/resources/search_people.png"))); // NOI18N
        buscarClienteBoton.setToolTipText("Buscar clientes");
        buscarClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteBotonActionPerformed(evt);
            }
        });

        agregarClienteBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda/presentation/view/resources/add_people.png"))); // NOI18N
        agregarClienteBoton.setToolTipText("Agregar un cliente");
        agregarClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteBotonActionPerformed(evt);
            }
        });

        apartadoBuscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda/presentation/view/resources/box_search.png"))); // NOI18N
        apartadoBuscarBoton.setToolTipText("Buscar apartados");
        apartadoBuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartadoBuscarBotonActionPerformed(evt);
            }
        });

        ingresarApartadoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda/presentation/view/resources/box_add.png"))); // NOI18N
        ingresarApartadoBoton.setToolTipText("Registrar un apartado");
        ingresarApartadoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarApartadoBotonActionPerformed(evt);
            }
        });

        abonoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda/presentation/view/resources/pay.png"))); // NOI18N
        abonoBoton.setToolTipText("Realizar un abono");
        abonoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abonoBotonActionPerformed(evt);
            }
        });

        bienvenidaLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bienvenidaLabel.setText("BIENVENIDOS A HAWAC SYSTEM ");
        bienvenidaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        usuarioBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda/presentation/view/resources/images.jpg"))); // NOI18N
        usuarioBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bienvenidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(ingresarApartadoBoton)
                        .addGap(133, 133, 133)
                        .addComponent(apartadoBuscarBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usuarioBt)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarClienteBoton)
                .addGap(132, 132, 132)
                .addComponent(agregarClienteBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abonoBoton)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioBt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bienvenidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarClienteBoton)
                            .addComponent(agregarClienteBoton)
                            .addComponent(abonoBoton))
                        .addGap(28, 28, 28)
                        .addComponent(ingresarApartadoBoton))
                    .addComponent(apartadoBuscarBoton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteBotonActionPerformed
 Application.CLIENTES_VIEW.setLocation(this.buscarClienteBoton.getLocationOnScreen());
 //controller.preAgregar();
     Application.CLIENTES_VIEW.setVisible(true);
    }//GEN-LAST:event_buscarClienteBotonActionPerformed

    private void agregarClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteBotonActionPerformed
         Application.CLIENTE_VIEW.setLocation(this.agregarClienteBoton.getLocationOnScreen());
 //controller.preAgregar();
     Application.CLIENTE_VIEW.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_agregarClienteBotonActionPerformed

    private void ingresarApartadoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarApartadoBotonActionPerformed
        Application.PRODUCTOS_VIEW.setLocation(this.agregarClienteBoton.getLocationOnScreen());
        Application.PRODUCTOS_VIEW.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ingresarApartadoBotonActionPerformed

    private void apartadoBuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartadoBuscarBotonActionPerformed
        // TODO add your handling code here:
       Application.APARTADOS_VIEW.setButto(false);
       Application.APARTADOS_VIEW.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_apartadoBuscarBotonActionPerformed

    private void abonoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abonoBotonActionPerformed
        // TODO add your handling code here:
        Application.APARTADOS_VIEW.setButto(true);
        Application.APARTADOS_VIEW.setVisible(true);
        
    }//GEN-LAST:event_abonoBotonActionPerformed

    private void usuarioBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioBtActionPerformed
        // TODO add your handling code here
        Application.USUARIOS_VIEW.setVisible(true);
    }//GEN-LAST:event_usuarioBtActionPerformed

//    public void setBienvenidaLabel(String bienvenidaLabel) {
//        this.bienvenidaLabel.setText( bienvenidaLabel);
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton abonoBoton;
    private javax.swing.JButton agregarClienteBoton;
    private javax.swing.JButton apartadoBuscarBoton;
    private javax.swing.JLabel bienvenidaLabel;
    private javax.swing.JButton buscarClienteBoton;
    public javax.swing.JButton ingresarApartadoBoton;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLbl;
    public javax.swing.JButton usuarioBt;
    // End of variables declaration//GEN-END:variables
}
